swagger:
  base:
    package: com.lvmoney.frame.pool.thread
  contact:
    email: author@lvmoney.com
    name: author
    url: ''
  description: frame demo 服务提供方
  title: authentication-resource
  url: ''
  version: 1.0
server:
  port: 9900