server:
  port: 8828
swagger:
  base:
    package: com.lvmoney.frame.ipfs.node.function
  contact:
    email: author@lvmoney.com
    name: author
    url: ''
  description: frame demo 服务提供方
  title: authentication-resource
  url: ''
  version: 1.0