server:
  port: 8093
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
swagger:
  base:
    package: com.lvmoney.frame.demo.mongdb
  contact:
    email: author@lvmoney.com
    name: author
    url: ''
  description: mongodb
  title: authentication-resource
  url: ''
  version: 1.0