spring:
  application:
    name: seata-provider
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  cloud:
    alibaba:
      seata:
        tx-service-group: sunrise_tx_group
  datasource:
    url: jdbc:mysql://localhost:3306/fescar2?useSSL=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8072
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    io.seata: debug