/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative */

#ifndef _Included_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
#define _Included_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
 * Method:    init
 * Signature: (Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaModelSetting;)J
 */
JNIEXPORT jlong JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
 * Method:    cropFace
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;[Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaPointF;)Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative_cropFace
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
 * Method:    predictAge
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;)I
 */
JNIEXPORT jint JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative_predictAge
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
 * Method:    predictAgeWithCrop
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;[Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative_predictAgeWithCrop
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
 * Method:    set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative_set
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
 * Method:    get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_AgePredictorNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
