/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative */

#ifndef _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
#define _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    init
 * Signature: (Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaModelSetting;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_init
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    predict
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaRect;[Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_predict
  (JNIEnv *, jclass, jlong, jobject, jobject, jobjectArray);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    predictVideo
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaRect;[Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_predictVideo
  (JNIEnv *, jclass, jlong, jobject, jobject, jobjectArray);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    resetVideo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_resetVideo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    getPreFrameScore
 * Signature: (J)Lcom/lvmoney/frame/ai/seetaface/jni/vo/PreFrameScore;
 */
JNIEXPORT jobject JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_getPreFrameScore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    setVideoFrameCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_setVideoFrameCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    getVideoFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_getVideoFrameCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    setThreshold
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_setThreshold
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    setBoxThresh
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_setBoxThresh
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    getBoxThresh
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_getBoxThresh
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    getThreshold
 * Signature: (J)Lcom/lvmoney/frame/ai/seetaface/jni/vo/PreFrameScore;
 */
JNIEXPORT jobject JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_getThreshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_set
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceAntiSpoofingNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
