/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative */

#ifndef _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative
#define _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative
 * Method:    init
 * Signature: (Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaModelSetting;)J
 */
JNIEXPORT jlong JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative
 * Method:    number
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative_number
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative
 * Method:    mark
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaRect;)[Lcom/lvmoney/frame/ai/seetaface/jni/vo/PointWithMask;
 */
JNIEXPORT jobjectArray JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative_mark
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceLandmarkerNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
