/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative */

#ifndef _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
#define _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    init
 * Signature: (Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaModelSetting;)J
 */
JNIEXPORT jlong JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    cropFace
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;[Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaPointF;)Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;
 */
JNIEXPORT jobject JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_cropFace
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    extractCroppedFace
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_extractCroppedFace
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    extract
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;[Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaPointF;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_extract
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    calculateSimilarity
 * Signature: (J[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_calculateSimilarity
  (JNIEnv *, jclass, jlong, jfloatArray, jfloatArray);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_set
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceRecognizerNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
