/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative */

#ifndef _Included_com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative
#define _Included_com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative
 * Method:    init
 * Signature: (Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaModelSetting;)J
 */
JNIEXPORT jlong JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative
 * Method:    detect
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaRect;)Lcom/lvmoney/frame/ai/seetaface/jni/vo/MaskStatus;
 */
JNIEXPORT jobject JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative_detect
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_MaskDetectorNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
