/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative */

#ifndef _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
#define _Included_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    init
 * Signature: (Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaModelSetting;II)J
 */
JNIEXPORT jlong JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_init
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    setSingleCalculationThreads
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_setSingleCalculationThreads
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    track
 * Signature: (JLcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaImageData;I)Lcom/lvmoney/frame/ai/seetaface/jni/vo/SeetaTrackingFaceInfoArray;
 */
JNIEXPORT jobject JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_track
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    setMinFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_setMinFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    getMinFaceSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_getMinFaceSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    setThreshold
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_setThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    getThreshold
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_getThreshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    setVideoStable
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_setVideoStable
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    getVideoStable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_getVideoStable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lvmoney_frame_ai_seetaface_jni_natives_FaceTrackerNative_close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
