spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  application:
    name: demoFile
server:
  port: 9904
swagger:
  base:
    package: com.lvmoney
  contact:
    email: author@lvmoney.com
    name: author
    url: ''
  description: frame demo 服务调用方
  title: authentication-resource
  url: ''
  version: 1.0
frame:
  swagger:
    support: true
  fileType:
    support: true