package com.zhy.drools
import com.zhy.frame.strategy.drools.vo.ResMessage

rule "LEVEL_1"
dialect "java"
 when
$resMessage:ResMessage(originalPrice>0&&originalPrice<=200)
 then
 $resMessage.setCost(5d);
   update($resMessage);
end
 
rule "LEVEL_2"
dialect "java"
 when
$resMessage:ResMessage(originalPrice>200&&originalPrice<=300)
 then
   $resMessage.setCost(10d);
   update($resMessage);
end

rule "LEVEL_3"
dialect "java"
 when
$resMessage:ResMessage(originalPrice>300&&originalPrice<=999999)
 then
   $resMessage.setCost(20d);
   update($resMessage);
end
