spring:
  application:
    name: admin-feign
  mail:
    host: smtp.qq.com
    port: 465
    username: 365619103@qq.com
    password: swcqthlofdkmbhcc
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  boot:
    admin:
      notify:
        mail:
          from: 365619103@qq.com
          to: 1300515928@qq.com
server:
  port: 8769
info:
  lvmoney:
    said: 握紧拳头，打拼自己的地盘