spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    clickhouse:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://10.20.128.235:8123/default?max_result_bytes=10000
      username: default
      paswword:
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
swagger:
  base:
    package: com.zhy.frame.demo.clickhouse.controller
  contact:
    email: author@zhy.com
    name: author
    url: ''
  description: frame demo 服务提供方
  title: authentication-resource
  url: ''
  version: 1.0
frame:
  swagger:
    support: true
server:
  port: 7766