swagger:
  base:
    package: com.lvmoney.frame.newsql.clickhouse.base.controller
  contact:
    email: author@lvmoney.com
    name: author
    url: ''
  description: frame demo 服务提供方
  title: authentication-resource
  url: ''
  version: 1.0
server:
  port: 7777
frame:
  swagger:
    support: true
  db:
    clickhouse:
      host: 192.168.10.74
      port: 8123
      user: default
      password:
      database: log_platform