spring:
  application:
    name: email-feign
  mail:
    host: smtp.qq.com
    port: 465
    username: 365619103@qq.com
    password:
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
server:
  port: 8769